AllCops:
  Exclude:
    - "vendor/**/*" # rubocop config/default.yml
    - "db/*"
    - 'config/**/*'
    - 'bin/*'

Metrics/LineLength:
  Exclude:
    - "Rakefile"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

Style/Documentation:
  Enabled: false