version: 2
jobs:
  build:
    working_directory: ~/a-chess/frontend-vue
    parallelism: 1
    shell: /bin/bash --login
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
          POSTGRES_USERNAME: hyuga
          POSTGRES_PASSWORD:

      - image: circleci/postgres:10-alpine-postgis
        environment:
          POSTGRES_USER: hyuga
          POSTGRES_DB: frontend_test
    
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-{{ checksum "Gemfile.lock" }}
            - rails-demo-
      
      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - run: sudo apt install -y postgresql-client || true

      # Store bundle cache
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      
      - run: bundle exec rubocop

      # yarn install
      - run: yarn

      # Setup the database
      - run: bundle exec rake db:create
      - run: bundle exec rake db:migrate

      # Precompile assets
      - run: bundle exec bin/webpack

      # Run the rspec
      - run: bundle exec rake rspec --color --fail-fast
