default: &default
  adapter: postgresql
  timeout: 5000
  host: <%= ENV['POSTGRES_HOST'] || ENV['RAILS_DATABASE_HOST'] || 'db' %>
  port: <%= ENV['POSTGRES_PORT'] || ENV['RAILS_DATABASE_PORT'] || 5432 %>
  username: <%= ENV['POSTGRES_USERNAME'] || ENV['RAILS_DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || ENV['RAILS_DATABASE_PASSWORD'] || ''%>
  pool: <%= (ENV['DB_CONNECTION_POOL_SIZE'] || "5").to_i %>
  encoding: unicode

development:
  <<: *default
  database: frontend_development

test:
  <<: *default
  database: frontend_test

production:
  database: frontend_production
